name: null
favicon: null
layout_spectrum: 0.10446559893898666
typography_spectrum: 0.4741011494770646
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.9756421688944101
  lightness: 0.9610947081819177
  saturation: 0.17271913215517998
  rhythmicContrast: 0.29931888706050813
purpose: []
