name: scworks
favicon: null
layout_spectrum: 0.10446559893898666
typography_spectrum: 0.50733
title: Seth Cheeks
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#dcdcdc'
    - '#18181a'
    - '#555459'
    - '#a1a0a5'
    - '#fb453a'
  brandStrength: 1
  lightness: 0.4375
  saturation: 0.3125
  rhythmicContrast: 1
purpose: []
